spring:
  config:
    import:
    - configserver:http://localhost:9191
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true 
  application:
    name: Payment-Service
    
server:
  port: 9095
  
logging:
  file:
    name: logs\microservice.log
    path: logs\